# Generated by Django 4.0.6 on 2022-08-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255)),
                ('totalprice', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('time', models.DateTimeField(max_length=255)),
                ('btiming', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='contact_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='register_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('epassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='signin_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('epassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='turf_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(default='', upload_to='turf')),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('ratings', models.CharField(max_length=255)),
                ('timing', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.register_tb')),
            ],
        ),
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoncard', models.CharField(max_length=255)),
                ('grandtotal', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.cart_tb')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.user_tb')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.register_tb')),
                ('turfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.turf_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.user_tb')),
            ],
        ),
        migrations.AddField(
            model_name='cart_tb',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.user_tb'),
        ),
        migrations.AddField(
            model_name='cart_tb',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.register_tb'),
        ),
        migrations.AddField(
            model_name='cart_tb',
            name='turfid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.turf_tb'),
        ),
    ]
